default: --no-source --color -f pretty -x
report_html: -f html -o relatorios/cucumber-html-report.html
report_json: -f json -o relatorios/cucumber-json-report.json
rerun_log: -f rerun -o cucumber_failures.txt
